server:
  port: ${MIPUERTO}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.30:3306/agencia?serverTimezone=UTC
    username: usuario
    password: password
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher        
eureka:
  client:
    service-url:
      defaultzone: http://192.168.3.30:8761/eureka
  instance:
    hostName: 192.168.0.30
    instance-id: ${spring.application.name}:${random.int}
